### ISSUE TITLE
@Reference throws java.lang.NoSuchMethodError: com.mongodb.DBRef.<init>(Ljava/lang/String;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by LmV4corbeau** [mongodb/morphia#797]
HI, i'm working with Morphia 1.0.0, jdk 1.8, Mongo 3.0 and trying to reference to simpel Objects.
The stacetrace is :
```
Exception in thread "main" java.lang.NoSuchMethodError: com.mongodb.DBRef.<init>(Ljava/lang/String;Ljava/lang/Object;)V
	at org.mongodb.morphia.mapping.Mapper.keyToRef(Mapper.java:739)
	at org.mongodb.morphia.mapping.ReferenceMapper.writeSingle(ReferenceMapper.java:60)
	at org.mongodb.morphia.mapping.ReferenceMapper.toDBObject(ReferenceMapper.java:48)
	at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:658)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:573)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:555)
	at org.mongodb.morphia.DatastoreImpl.entityToDBObj(DatastoreImpl.java:971)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1018)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1097)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1080)
	at org.toschu.repository.api.Implemented.MongoDBMorphia.persist(MongoDBMorphia.java:177)
	at org.toschu.repository.api.Repository$$Lambda$1/1800890735.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.toschu.repository.api.Repository.persist(Repository.java:45)
```

The Objects are Person :
```
@Entity
public class Person extends Identity {

    @Id
    private ObjectId objId;
    private String name;
    private String surname;
    private List<String> hobbys;

    @Reference
    private Adress adress;

    public Person() {
        this.objId = new ObjectId();
    }
```
and Adress
```
@Entity
public class Adress extends Identity {

    @Id
    private ObjectId objId;
    private String street;
    private String zipCode;
    private String housNumber;
    private String country;
    private String fedralState;

    public Adress() {
        this.objId = new ObjectId();
    }
```

I can't find any solution one the web

Please help me

**Comment by evanchooly** [comment]
What version of the driver are you using?  The minimum version required is 3.0.0.

**Comment by LmV4corbeau** [comment]
OK, my fauled. i was on an older driver. sry for waysting time

**Comment by evanchooly** [comment]
No worries.  That means the fix is easy.  :)
